---
title: "Lab option"
author: "Zheqi Wu"
date: "6/6/2018"
output: pdf_document
---

## Problem 1

```{r}
#Read your csv file:
data <- read.csv("option.csv", sep=",", header=TRUE)

# estimate the annual volatility
table=data.frame("pi"=data[-1,3:ncol(data)],"pi-1"=data[-nrow(data),3:ncol(data)],"pi/pi-1"=data[-1,3:ncol(data)]/data[-nrow(data),3:ncol(data)])
table$u=log(table[3])

s2=sqrt((sum(table$u^2)-sum(table$u)^2/nrow(table))/(nrow(table)-1))
sigma=s2/sqrt(1/252)
cat('sigma =',sigma )
mu=mean(table$pi.1)
sd=sd(table$pi.1)
```

## Problem 2
```{r}

## 74 trade days from June 5 to Sep 21
## choose exercise price at E=S0=242.56
#1.  Monte Carlo simulations.
#Initialize vector of stock prices (last price in each path).
St <- rep(0, 10000)

#Stock price now.
S0 <- 242.56

#Initialize vector of stock prices.
S <- c(S0,rep(0,74))

#Inputs.
r <- .05
sigma <- sigma
dt <- 1/252

#Loops.
for(j in (1:10000)){
	epsilon <- rnorm(74)
for(i in(1:74)) {
   S[i+1] <- S[i]*exp((r-sigma^2/2)*dt + sigma*epsilon[i]*sqrt(dt))       
                      }
St[j] <- S[75]

}

#Price of the call option
E <- 242.56  #Exercise price.
diff <- St-E  
payoff <- sum(diff[diff>0]) / 10000

C <- payoff*exp(-r*74/252)
cat("C =",C)
```


## Problem 3
```{r}
t <- 74/252
n <- 30
u <- exp(sigma*sqrt(t/n))
d <- 1/u

p <- (exp(r*t/n)-d) / (u-d)
p1 <- (p*u) / exp(r*t/n)

k <- log(E/(d^n*S0)) / log(u/d)

C <- S0 * pbinom(ceiling(k)-1, n, p1, lower.tail=FALSE) - 
    E*exp(-r*t)*pbinom(ceiling(k)-1, n, p, lower.tail=FALSE)
cat("C =",C)
```

## Problem 4

```{r}
t <- 74/252
d1 <- (log(S0/E) + (r+.5*sigma^2)*t) / (sigma*sqrt(t))
d2 <- d1 - sigma*sqrt(t)

C <- S0*pnorm(d1) - E*exp(-r*t)*pnorm(d2)
cat("C =",C)
```


